- package.json
- yarn.lock
monthly update with more updates and fixes.
> upgraded types, commander, typescript

- package.json
- src/migrate/ghostMigrationProvider.ts
- src/migrate/wordpressMigrationProvider.ts
- test/migrate/ghostMigrationProvider.test.ts
- test/migrate/wordpressMigrationProvider.test.ts
> feat: replace node-fetch for axios

- packages/writr-cli/package.json
> upgrading typescript to 4.9.5

- packages/writr-cli/package.json
> upgrading fs-extra to 11.1.1

- packages/writr-cli/package.json
upgrading typescript and types to latest
> upgrading typescript and types to latest

- .github/workflows/tests.yml
- packages/writr-cli/package.json
> upgrading parse-json to 7.0.0

- packages/writr-cli/package.json
> upgrading ecto to 2.1.10

- packages/writr-cli/package.json
> upgrading commander to 10.0.1

- packages/writr-cli/package.json
> upgrading axios to 1.4.0

- packages/writr-cli/package.json
> upgrading ecto to 2.1.11

- package.json
upgrading @types/node to 20.2.5
> upgrading @types/node to 20.2.5

- packages/writr-cli/package.json
> upgrading winston to 3.9.0

- packages/writr-cli/package.json
upgrading browser-sync to 2.29.3
> upgrading browser-sync to 2.29.3

- packages/writr-cli/package.json
upgrading typescript ts-node and @types/node to latest
> upgrading typescript ts-node and @types/node to latest

- packages/writr-cli/package.json
> upgrading ecto to 2.1.12

- packages/writr-cli/package.json
> upgrading commander to 11.0.0

- packages/writr-cli/package.json
> upgrading winston to 3.10.0

- packages/writr-cli/package.json
> upgrading inquirer to 9.2.9

- packages/writr-cli/package.json
> upgrading ecto to 2.1.13

- src/helpers.ts
- test/fixtures/readme-example.md
- test/helpers.test.ts
adding in helpers for frontmatter and createdoc
> adding in helpers for frontmatter and createdoc

- bin/writr.js
- src/console.ts
- src/writr.ts
> Adding in console support

- package.json
upgrading ecto to latest version
> upgrading ecto to latest version

- test/console.test.ts
- test/writr.test.ts
updating unit testing for WritrConsole
> updating unit testing for WritrConsole

- package.json
- site/writr.config.ts
- src/console.ts
- src/writr.ts
- test/console.test.ts
- test/writr.test.ts
- tsconfig.build.json
- tsconfig.json
updater notifications and execution parsing
> updater notifications and execution parsing

- package.json
- vitest.config.mjs
> upgrading vitest to 1.0.4

- package.json
upgrading typescript to 5.3.3 and types
> upgrading typescript to 5.3.3 and types

- .github/PULL_REQUEST_TEMPLATE.md
- package.json
> upgrading ecto to 2.2.4

- package.json
> upgrading fs-extra to 11.2.0

- src/console.ts
- src/writr.ts
- test/console.test.ts
> adding in templatePath option

- .gitignore
- init/variables.css
- site/variables.css
- src/writr.ts
- template/css/home.css
- template/css/index.css
- template/css/variables.css
- test/fixtures/multi-page-site/variables.css
- test/fixtures/single-page-site/variables.css
- test/writr.test.ts
Adding in single page template
> Adding in single page template

- package.json
> upgrading vitest to latest

- src/builder.ts
- src/github.ts
- test/builder.test.ts
> github data in build

- src/builder.ts
- test/builder.test.ts
- test/fixtures/template-example/css/home.css
- test/fixtures/template-example/css/index.css
- test/fixtures/template-example/css/variables.css
> adding in template data

- src/builder.ts
- test/builder.test.ts
- test/fixtures/multi-page-site/robots.txt
> adding in robots.txt support

- src/builder.ts
- test/builder.test.ts
> adding in sitemap

- src/builder.ts
- template/index.hbs
- test/builder.test.ts
> building the index page

- src/builder.ts
- template/releases.hbs
- test/builder.test.ts
- test/github.test.ts
adding in github release build
> adding in github release build

- src/builder.ts
adding into build release page build
> adding into build release page build

- src/builder.ts
- test/builder.test.ts
adding in time execution on build
> adding in time execution on build

- src/github.ts
- src/writr.ts
- test/builder.test.ts
- test/github.test.ts
- test/writr.test.ts
> adding in mocks for axios

- src/writr.ts
- test/writr.test.ts
> handing build output path

- src/writr.ts
- test/writr.test.ts
removing log output on certain tests
> removing log output on certain tests

- package.json
- src/options.ts
- test/options.test.ts
updating to use relative paths on options
> updating to use relative paths on options

- src/builder.ts
- src/options.ts
- test/builder.test.ts
> fixing pathing issue number 2

- package.json
- src/builder.ts
- template/index.hbs
Adding in githubPath to WritrData
> Adding in githubPath to WritrData

- .github/workflows/deploy-site.yml
- package.json
> updating site deployment

- README.md
- package.json
- src/writr.ts
- test/writr.test.ts
Adding in math support with katex
> Adding in math support with katex

- README.md
- package.json
- src/writr.ts
- test/writr.test.ts
fixing index.js reference and updating options
> fixing index.js reference and updating options

- README.md
- package.json
- src/writr.ts
- test/writr.test.ts
Adding in render react and render react sync for jsx element
> Adding in render react and render react sync for jsx element

- package.json
> upgrading xo to 0.57.0

- CONTRIBUTING.md
- SECURITY.md
- package.json
- vitest.config.mjs
> upgrading xo to 0.58.0

- package.json
upgrading typescript and webpack to latest
> upgrading typescript and webpack to latest

- .github/workflows/deploy-site.yml
- package.json
> upgrading vitest to 1.4.0

- README.md
- package.json
- site/docula.config.cjs
> upgrading docula to 0.5.2

- package.json
upgrading html-react-parser to 5.1.10
> upgrading html-react-parser to 5.1.10

- package.json
> upgrading typescript to 5.4.5

- package.json
> upgrading docula to 0.5.3

- package.json
> upgrading react to 18.3.1

- package.json
moving ts-node to devDependency
> moving ts-node to devDependency

- src/writr.ts
removing processor from unified as not used
> removing processor from unified as not used

- package.json
upgrading typescript and webpack to lastest
> upgrading typescript and webpack to lastest

- package.json
> upgrading unified to 11.0.5

- package.json
upgrading remark-emoji to 5.0.1
> upgrading remark-emoji to 5.0.1

- package.json
upgrading rehype-katex to 7.0.1
> upgrading rehype-katex to 7.0.1

- package.json
upgrading html-react-parser to 5.1.15
> upgrading html-react-parser to 5.1.15

- src/writr.ts
- test/writr.test.ts
BREAKING CHANGE - moving markdown to its own property
> BREAKING CHANGE - moving markdown to its own property

- README.md
updating readme with new changes on markdown
> updating readme with new changes on markdown

- README.md
- package.json
- src/writr-cache.ts
- src/writr.ts
- test/writr-cache.test.ts
- test/writr.test.ts
> Caching for markdown rendering

- package.json
> upgrading typescript to 5.6.2

- package.json
> upgrading docula to 0.9.1

- package.json
- tsconfig.json
attempting support for CommonJS via tsup
> attempting support for CommonJS via tsup

- README.md
- package.json
- src/writr-cache.ts
> upgrading cacheable to 1.8.0

- package.json
- src/writr-cache.ts
- test/writr.test.ts
moving to node:fs and node:crypto
> moving to node:fs and node:crypto

- test/writr.test.ts
removing console.log from production code
> removing console.log from production code

- package.json
> upgrading keyv to 5.1.2

- package.json
> upgrading cacheable to 1.8.2

- package.json
> upgrading remark-mdx to 3.1.0

- package.json
updating rehype-highlight to 7.0.1
> updating rehype-highlight to 7.0.1

- package.json
upgrading typescript, tsup, and types to latest
> upgrading typescript, tsup, and types to latest

- README.md
- package.json
- src/writr.ts
- test/content-fixtures.ts
- test/writr.test.ts
adding in emit on yaml parsing of front matter
> adding in emit on yaml parsing of front matter

- README.md
- package.json
- src/writr-cache.ts
- src/writr.ts
- test/writr-cache.test.ts
- test/writr-render.test.ts
- test/writr.test.ts
Caching feature disabled by default and in memory only
> Caching feature disabled by default and in memory only

- package.json
- src/writr-cache.ts
upgrading typescript, webpack, and @types/node to latest
> upgrading typescript, webpack, and @types/node to latest

- package.json
> upgrading hookified to 1.5.1

- src/writr.ts
- test/writr.test.ts
> fixing render and options

- README.md
- src/writr.ts
- test/writr-render.test.ts
- test/writr.test.ts
adding in renderToFile and renderToFileSync
> adding in renderToFile and renderToFileSync

- package.json
> upgrading react to 19.0.0

- package.json
> upgrading cacheable to 1.8.7

- package.json
> upgrading hookified to 1.6.0

- .github/workflows/code-coverage.yml
- .github/workflows/deploy-site.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- CONTRIBUTING.md
- README.md
> migrating to pnpm as default

- README.md
- src/writr.ts
- test/writr-hooks.test.ts
Adding in hooks for render and renderSync
> Adding in hooks for render and renderSync

- README.md
fixing to only have body as the option on renderData object
> fixing to only have body as the option on renderData object

- package.json
chore: upgrading tsup and typescript to latest
> chore: upgrading tsup and typescript to latest

- package.json
chore: upgrading hookified to 1.7.0
> chore: upgrading hookified to 1.7.0

- README.md
- src/writr.ts
- test/writr-hooks.test.ts
feat: adding in hooks for beforeSaveToFile
> feat: adding in hooks for beforeSaveToFile

- src/writr.ts
feat: updating functions with public to be same style
> feat: updating functions with public to be same style

- package.json
chore: upgrading hookified to 1.7.1
> chore: upgrading hookified to 1.7.1

- package.json
chore: upgrading remark-gfm to 4.0.1
> chore: upgrading remark-gfm to 4.0.1

- package.json
chore: upgrading rehype-highlight to 7.0.2
> chore: upgrading rehype-highlight to 7.0.2

- README.md
- src/writr.ts
- test/fixtures/load-from-file.md
- test/writr-hooks.test.ts
feat: adding in hooks for loadFromFile
> feat: adding in hooks for loadFromFile

- README.md
feat: adding in support for jsDelivr
> feat: adding in support for jsDelivr

- package.json
chore: upgrading typescript to 5.8.2
> chore: upgrading typescript to 5.8.2

- package.json
chore: upgrading react to 19.1.0
> chore: upgrading react to 19.1.0

- package.json
chore: upgrading hookified to 1.8.1
> chore: upgrading hookified to 1.8.1

- package.json
chore: upgrading cacheable to 1.8.9
> chore: upgrading cacheable to 1.8.9

- package.json
chore: upgrading html-react-parser to 5.2.3
> chore: upgrading html-react-parser to 5.2.3

- package.json
chore: upgrading hookified to 1.8.2
> chore: upgrading hookified to 1.8.2

- package.json
chore: upgrading remark-rehype to 11.1.2
> chore: upgrading remark-rehype to 11.1.2

- package.json
- pnpm-workspace.yaml
- test/writr.test.ts
chore: upgrading tsup to 8.5.0
> chore: upgrading tsup to 8.5.0

- package.json
chore: upgrading html-react-parser to 5.2.5
> chore: upgrading html-react-parser to 5.2.5

- package.json
chore: upgrading hookified to 1.9.0
> chore: upgrading hookified to 1.9.0

- package.json
chore: upgrading cacheable to 1.9.0
> chore: upgrading cacheable to 1.9.0

- README.md
- src/writr-cache.ts
fix: reverting back documentation that doesnt work
> fix: reverting back documentation that doesnt work

- package.json
chore: upgrading hookified to 1.9.1
> chore: upgrading hookified to 1.9.1

- package.json
chore: upgrading cacheable to 1.10.0
> chore: upgrading cacheable to 1.10.0

- package.json
chore: upgrading webpack to 5.100.2
> chore: upgrading webpack to 5.100.2

- package.json
chore: upgrading hookified to 1.11.0
> chore: upgrading hookified to 1.11.0

- package.json
chore: upgrading docula to 0.13.1
> chore: upgrading docula to 0.13.1

- README.md
- package.json
chore: upgrading typescript to 5.9.2
> chore: upgrading typescript to 5.9.2

- package.json
chore: upgrading cacheable to 1.10.4
> chore: upgrading cacheable to 1.10.4

- .gitignore
- README.md
- src/writr.ts
- test/writr.test.ts
feat: adding in validate and validateSync functions
> feat: adding in validate and validateSync functions

- package.json
chore: upgrading cacheable to 2.0.2
> chore: upgrading cacheable to 2.0.2

- package.json
chore: upgrading remark-mdx to 3.1.1
> chore: upgrading remark-mdx to 3.1.1

- package.json
chore: upgrading remark-emoji to 5.0.2
> chore: upgrading remark-emoji to 5.0.2
